In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
#IMPORTING DATA
df=pd.read_csv('Advertising.csv')
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
#Removing the unwanted column
df=df.drop('Unnamed: 0',axis=1)
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X=df.drop('Sales',axis=1)
y=df['Sales']
print(X.head(2))
print(y)

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64


CONVERSION TO POLYNOMIAL FEATURES

In [6]:
from sklearn.preprocessing import PolynomialFeatures
poly_conveter=PolynomialFeatures(degree=3,include_bias=False)
poly_feature=poly_conveter.fit_transform(X)
poly_feature

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [7]:
#shape of polyfeature
poly_feature.shape

(200, 19)

In [8]:
#Now to train test split
from sklearn.model_selection import train_test_split

In [9]:
 X_train, X_test, y_train, y_test = train_test_split(poly_feature, y, test_size=0.33, random_state=101)

In [10]:
X_train.shape

(134, 19)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
X_train

array([[ 0.455913  , -0.15469995, -0.98899258, ..., -0.60618091,
        -0.56426029, -0.5063835 ],
       [-0.84432792,  1.60997604,  0.21389931, ...,  1.27808026,
         0.25379368, -0.22928072],
       [-0.2808111 ,  0.93019813,  2.36467003, ...,  2.13064753,
         2.9262847 ,  2.91162153],
       ...,
       [ 1.07281562, -1.32199535,  0.32937694, ..., -0.70151704,
        -0.50832904, -0.16601335],
       [ 0.77504147,  0.04442691, -1.2536288 , ..., -0.6570423 ,
        -0.58737703, -0.51185147],
       [ 0.16525695,  0.56627662,  1.09922775, ...,  0.67742414,
         0.75141387,  0.50797559]])

In [23]:
X_test

array([[-0.88585021,  1.78850357,  0.75279488, ...,  2.22798415,
         0.9755699 ,  0.14551054],
       [ 1.25788641,  0.24355378, -1.18145529, ..., -0.61277508,
        -0.58084279, -0.5111459 ],
       [-0.43266405, -0.40875836,  0.41117359, ..., -0.40920535,
        -0.19900549, -0.11591485],
       ...,
       [ 0.39422273,  1.56877738,  1.37829867, ...,  2.5916401 ,
         1.82738108,  0.88170373],
       [ 0.86639051, -1.30826246,  0.95006916, ..., -0.69357908,
        -0.43106057,  0.33891475],
       [ 1.2045006 ,  0.90273235,  2.03267186, ...,  1.82640722,
         2.30795806,  2.0924344 ]])

**LASSO REGRESSION**<br>
two main important reason of using Lasso Regression<br>
1):Regularization<br>
2):Feature slecation<br>

In [24]:
from sklearn.linear_model import LassoCV

In [25]:
lasso_cv_model=LassoCV(eps=0.001, cv=5, n_alphas=100,max_iter=10000)


In [26]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=10000)

In [27]:
lasso_cv_model.alpha_

0.0048358593581782185

In [28]:
test_predication=lasso_cv_model.predict(X_test)

In [29]:
lasso_cv_model.coef_

array([ 4.87579961,  0.11802077,  0.24018055, -5.01491275,  4.36541863,
       -0.22918399, -0.        ,  0.03860951, -0.        ,  1.82671866,
       -0.80741429,  0.        ,  0.13108636, -0.        , -0.        ,
        0.        ,  0.        ,  0.        , -0.        ])

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [31]:
MAE=mean_absolute_error(y_test,test_predication)
MAE

0.4236488496303265

In [35]:
RMAE_lasso=np.sqrt(mean_squared_error(y_test,test_predication))
RMAE_lasso

0.5892189905548042