IMPORTING IMPORTANT LIBRARIES

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
#IMPORTING DATA
df=pd.read_csv('Advertising.csv')
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [8]:
#Removing the unwanted column
df=df.drop('Unnamed: 0',axis=1)
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [13]:
X=df.drop('Sales',axis=1)
y=df['Sales']
print(X.head(2))
print(y)

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64


CONVERSION TO POLYNOMIAL FEATURES

In [14]:
from sklearn.preprocessing import PolynomialFeatures
poly_conveter=PolynomialFeatures(degree=3,include_bias=False)
poly_feature=poly_conveter.fit_transform(X)
poly_feature

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [15]:
#shape of polyfeature
poly_feature.shape

(200, 19)

In [16]:
#Now to train test split
from sklearn.model_selection import train_test_split

In [17]:
 X_train, X_test, y_train, y_test = train_test_split(poly_feature, y, test_size=0.33, random_state=101)

X_train.shape

Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [21]:
X_train

array([[ 0.455913  , -0.15469995, -0.98899258, ..., -0.60618091,
        -0.56426029, -0.5063835 ],
       [-0.84432792,  1.60997604,  0.21389931, ...,  1.27808026,
         0.25379368, -0.22928072],
       [-0.2808111 ,  0.93019813,  2.36467003, ...,  2.13064753,
         2.9262847 ,  2.91162153],
       ...,
       [ 1.07281562, -1.32199535,  0.32937694, ..., -0.70151704,
        -0.50832904, -0.16601335],
       [ 0.77504147,  0.04442691, -1.2536288 , ..., -0.6570423 ,
        -0.58737703, -0.51185147],
       [ 0.16525695,  0.56627662,  1.09922775, ...,  0.67742414,
         0.75141387,  0.50797559]])

In [22]:
X_test

array([[-0.88585021,  1.78850357,  0.75279488, ...,  2.22798415,
         0.9755699 ,  0.14551054],
       [ 1.25788641,  0.24355378, -1.18145529, ..., -0.61277508,
        -0.58084279, -0.5111459 ],
       [-0.43266405, -0.40875836,  0.41117359, ..., -0.40920535,
        -0.19900549, -0.11591485],
       ...,
       [ 0.39422273,  1.56877738,  1.37829867, ...,  2.5916401 ,
         1.82738108,  0.88170373],
       [ 0.86639051, -1.30826246,  0.95006916, ..., -0.69357908,
        -0.43106057,  0.33891475],
       [ 1.2045006 ,  0.90273235,  2.03267186, ...,  1.82640722,
         2.30795806,  2.0924344 ]])

In [24]:
X_train.std()#standertization

1.0

**Ridge Regression**


In [26]:
#I am importing simple Ridge Regression 
from sklearn.linear_model import Ridge
model1=Ridge(alpha=1.0)
model1.fit(X_train,y_train)

Ridge()

In [27]:
#y_test predication
y_test_predication=model1.predict(X_test)
y_test_predication

array([13.70225944, 19.21634878, 12.23045389, 16.66763721,  8.28093015,
        7.41808526, 20.0021412 , 17.30864475, 10.36428224, 20.02636723,
        9.5244017 , 13.86523252, 12.20964851, 23.59795057, 19.76801616,
        9.44515379, 12.55164992,  9.05324068,  8.58771611, 21.61148284,
        7.56279628, 19.33367841, 27.53350704, 24.68043905,  8.98464492,
       11.83145613, 20.41094217,  9.24821994, 12.55104893,  8.41432047,
        8.86632344, 20.12267516, 10.71189555,  7.27003042, 18.20121251,
        9.25314307, 10.27343363,  9.47358602,  7.72500417, 10.86892208,
       12.65953092, 10.46212265, 11.14688729,  7.8917644 , 11.47192544,
       10.37676014,  6.75071177, 15.40002706, 13.23548724, 22.86151935,
       10.49261668, 13.14842286, 14.45128659, 11.68455829, 11.72025033,
        6.23154823, 25.24151675,  9.57107123, 17.34174892, 15.58090291,
       15.35650612, 25.76986802,  8.41786166, 21.73963928, 12.36667987,
       22.29201644])

**MODEL EVALUATION**

In [28]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [29]:
MAE_Ridge=mean_absolute_error(y_test,y_test_predication)
MAE_Ridge

0.5181992225168717

In [30]:
RMAE_Ridge=np.sqrt(mean_squared_error(y_test,y_test_predication))
RMAE_Ridge

0.7088689087899112

**CHOSSING BEST ALPHA VALUE**

we will need to do use cross validation to test a varity 
of alpha parameter on cross validation

In [33]:
from sklearn.linear_model import RidgeCV
model2=RidgeCV(alphas=(0.1, 1.0, 10.0))
model2.fit(X_train,y_train)

RidgeCV()

In [38]:
#selected alpha value
model2.alpha_

0.1

In [39]:
#model y test predication
y_test_predication_ridgeCV=model2.predict(X_test)
y_test_predication_ridgeCV

array([14.29441804, 19.09274078, 12.45657835, 17.11697952,  7.92213878,
        7.11055875, 19.93908808, 17.24961432, 10.28682469, 19.85631473,
        9.37140245, 13.93676075, 11.8445631 , 23.3175409 , 19.29359581,
        9.42610569, 12.44613111,  9.16152967,  8.70067319, 21.41727474,
        7.15087583, 19.37390792, 27.26727867, 24.39398038,  9.19780238,
       11.48707963, 20.44799653,  9.45981126, 12.54834966,  8.39919149,
        8.76754192, 19.91732307, 10.77004173,  7.09693457, 18.17538915,
        9.29856785, 10.54291059,  9.67413599,  7.29781737, 10.72290686,
       12.32886379, 10.33331507, 11.39742423,  7.7308797 , 11.73748995,
       10.61128497,  5.73452753, 15.35361927, 13.03794426, 22.67420852,
       10.59986712, 12.96502029, 14.74166515, 11.9969133 , 11.35618865,
        5.47887637, 24.94004856,  9.41141507, 17.2652532 , 15.60820308,
       15.14933107, 25.70639693,  8.49758236, 21.54616003, 12.12953788,
       21.98002659])

In [41]:
#parameter of x
model2.coef_

array([ 5.32298502,  0.6340435 ,  0.45082   , -6.01678743,  4.5650384 ,
       -1.05529106, -1.25112885,  0.47865005, -0.21808315,  2.49274371,
       -1.43382273,  0.77165384,  0.70388686, -0.28850266,  0.18532879,
        0.48908704, -0.1470775 , -0.01268636, -0.03643881])

In [42]:
#Model Evaluation
MAE_RidgeCV=mean_absolute_error(y_test,y_test_predication_ridgeCV)
MAE_RidgeCV

0.41901199532323763

In [43]:
RMAE_RidgeCV=np.sqrt(mean_squared_error(y_test,y_test_predication_ridgeCV))
RMAE_RidgeCV

0.6006703026820097